definitions:
  controller.DeleteRequestBody:
    type: object
  model.PizzaCategory:
    properties:
      des:
        type: string
      limit_Order:
        type: integer
      lsizePrice:
        type: integer
      msizePrice:
        type: integer
      name:
        type: string
      order_status:
        type: boolean
    type: object
info:
  contact: {}
paths:
  /admin/category:
    delete:
      consumes:
      - application/json
      description: 피자정보를 update하는 api
      parameters:
      - description: delete
        in: body
        name: DeleteRequestBody
        required: true
        schema:
          $ref: '#/definitions/controller.DeleteRequestBody'
      produces:
      - application/json
      responses: {}
      summary: delete a pizza in category
    post:
      consumes:
      - application/json
      description: 피자종류를 추가하는 api
      parameters:
      - description: PizzaCategory Info
        in: body
        name: model.PizzaCategory
        required: true
        schema:
          $ref: '#/definitions/model.PizzaCategory'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.PizzaCategory'
      summary: add a pizza in category
    put:
      consumes:
      - application/json
      description: 피자정보를 update하는 api
      parameters:
      - description: PizzaCategory Info
        in: body
        name: model.PizzaCategory
        required: true
        schema:
          $ref: '#/definitions/model.PizzaCategory'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.PizzaCategory'
      summary: update a pizza in category
  /health:
    get:
      description: health check
      responses: {}
      summary: health check
swagger: "2.0"
